import React, { useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { DailyLog, CycleSettings } from '../types';

interface TodayReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  todayLog: DailyLog | null;
  cycleSettings: CycleSettings;
  profile: { full_name?: string };
}

const TodayReportModal: React.FC<TodayReportModalProps> = ({
  isOpen,
  onClose,
  todayLog,
  cycleSettings,
  profile
}) => {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportType, setExportType] = useState<'png' | 'pdf' | null>(null);
  const today = new Date();
  
  const formatDate = (date: Date) => {
    return date.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  const flowText = (flow?: string) => {
    if (!flow) return 'Not logged';
    const flowMap: Record<string, string> = {
      'spotting': '💧 Spotting',
      'light': '💧 Light Flow',
      'medium': '💧💧 Medium Flow',
      'heavy': '💧💧💧 Heavy Flow'
    };
    return flowMap[flow] || flow;
  };

  const exportAsPNG = async () => {
    if (!cardRef.current) return;
    setIsExporting(true);
    setExportType('png');
    
    // Small delay to ensure card renders
    await new Promise(r => setTimeout(r, 100));
    
    try {
      const canvas = await html2canvas(cardRef.current, {
        scale: 3,
        backgroundColor: null,
        useCORS: true
      });
      
      const link = document.createElement('a');
      link.download = `Twilight_Today_${today.toISOString().split('T')[0]}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      onClose();
    } catch (error) {
      console.error('Failed to export PNG:', error);
      alert('Failed to export image. Please try again.');
    }
    
    setIsExporting(false);
    setExportType(null);
  };

  const exportAsPDF = async () => {
    if (!cardRef.current) return;
    setIsExporting(true);
    setExportType('pdf');
    
    await new Promise(r => setTimeout(r, 100));
    
    try {
      const canvas = await html2canvas(cardRef.current, {
        scale: 3,
        backgroundColor: null,
        useCORS: true
      });
      
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      
      const scale = (pdfWidth - 40) / imgWidth;
      const scaledWidth = imgWidth * scale;
      const scaledHeight = imgHeight * scale;
      
      const x = (pdfWidth - scaledWidth) / 2;
      const y = 30;
      
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(16);
      pdf.setTextColor(152, 67, 105);
      pdf.text('Daily Health Report', pdfWidth / 2, 20, { align: 'center' });
      
      pdf.addImage(imgData, 'PNG', x, y, scaledWidth, scaledHeight);
      
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Twilight Garden', pdfWidth / 2, pdfHeight - 10, { align: 'center' });
      
      pdf.save(`Twilight_Today_${today.toISOString().split('T')[0]}.pdf`);
      onClose();
    } catch (error) {
      console.error('Failed to export PDF:', error);
      alert('Failed to export PDF. Please try again.');
    }
    
    setIsExporting(false);
    setExportType(null);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
          onClick={onClose}
        >
          {/* Simple Format Selection Popup */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ type: 'spring', duration: 0.4 }}
            className="bg-white dark:bg-[#1a1a1f] rounded-2xl p-6 max-w-xs w-full shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <h2 className="text-lg font-bold text-gray-900 dark:text-white text-center mb-2">
              Export Today's Report
            </h2>
            <p className="text-sm text-gray-500 dark:text-gray-400 text-center mb-6">
              Choose your preferred format
            </p>
            
            <div className="flex flex-col gap-3">
              <button
                onClick={exportAsPNG}
                disabled={isExporting}
                className="flex items-center justify-center gap-3 py-4 px-6 bg-gradient-to-r from-pink-500 to-purple-600 text-white rounded-xl font-semibold hover:opacity-90 transition-all disabled:opacity-50"
              >
                <span className="material-symbols-outlined">image</span>
                {exportType === 'png' ? 'Generating...' : 'PNG Image'}
              </button>
              
              <button
                onClick={exportAsPDF}
                disabled={isExporting}
                className="flex items-center justify-center gap-3 py-4 px-6 bg-gradient-to-r from-blue-500 to-indigo-600 text-white rounded-xl font-semibold hover:opacity-90 transition-all disabled:opacity-50"
              >
                <span className="material-symbols-outlined">picture_as_pdf</span>
                {exportType === 'pdf' ? 'Generating...' : 'PDF Document'}
              </button>
            </div>
            
            <button
              onClick={onClose}
              className="w-full mt-4 py-2 text-gray-500 dark:text-gray-400 text-sm hover:text-gray-700 dark:hover:text-gray-200 transition-colors"
            >
              Cancel
            </button>
          </motion.div>

          {/* Hidden Card for Export - Not visible */}
          <div className="fixed -left-[9999px] top-0">
            <div 
              ref={cardRef}
              className="rounded-2xl p-6 w-[360px] relative overflow-hidden"
              style={{
                background: 'linear-gradient(135deg, #984369 0%, #BE123C 50%, #7C3AED 100%)'
              }}
            >
              {/* Decorative circles */}
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full" style={{ transform: 'translate(50%, -50%)' }}></div>
              <div className="absolute bottom-0 left-0 w-24 h-24 bg-white/5 rounded-full" style={{ transform: 'translate(-50%, 50%)' }}></div>
              
              {/* Content */}
              <div className="relative z-10">
                <div className="mb-6">
                  <p className="text-white/70 text-xs font-medium uppercase tracking-wider mb-1">
                    {formatDate(today)}
                  </p>
                  <h3 className="text-white text-xl font-bold">
                    {profile.full_name?.split(' ')[0] || 'My'}'s Daily Report
                  </h3>
                </div>

                <div className="bg-white/15 backdrop-blur-sm rounded-xl p-4 mb-4">
                  <p className="text-white/70 text-xs uppercase tracking-wider mb-1">Flow</p>
                  <p className="text-white text-lg font-semibold">
                    {flowText(todayLog?.flow)}
                  </p>
                </div>

                <div className="bg-white/15 backdrop-blur-sm rounded-xl p-4 mb-4">
                  <p className="text-white/70 text-xs uppercase tracking-wider mb-2">Symptoms</p>
                  {todayLog?.symptoms && todayLog.symptoms.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {todayLog.symptoms.map((symptom, i) => (
                        <span 
                          key={i}
                          className="px-3 py-1 bg-white/20 rounded-full text-white text-sm font-medium"
                        >
                          {symptom}
                        </span>
                      ))}
                    </div>
                  ) : (
                    <p className="text-white/80 text-sm">No symptoms logged</p>
                  )}
                </div>

                <div className="bg-white/15 backdrop-blur-sm rounded-xl p-4 mb-4">
                  <p className="text-white/70 text-xs uppercase tracking-wider mb-2">Mood</p>
                  {todayLog?.moods && todayLog.moods.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {todayLog.moods.map((mood, i) => (
                        <span 
                          key={i}
                          className="px-3 py-1 bg-white/20 rounded-full text-white text-sm font-medium capitalize"
                        >
                          {mood}
                        </span>
                      ))}
                    </div>
                  ) : (
                    <p className="text-white/80 text-sm">No mood logged</p>
                  )}
                </div>

                {todayLog?.notes && (
                  <div className="bg-white/15 backdrop-blur-sm rounded-xl p-4 mb-4">
                    <p className="text-white/70 text-xs uppercase tracking-wider mb-1">Notes</p>
                    <p className="text-white text-sm">{todayLog.notes}</p>
                  </div>
                )}

                <div className="flex items-center justify-between mt-4 pt-4 border-t border-white/10">
                  <div>
                    <p className="text-white/70 text-xs">Cycle Day</p>
                    <p className="text-white text-2xl font-bold">
                      {cycleSettings.lastPeriodStart 
                        ? Math.floor((today.getTime() - new Date(cycleSettings.lastPeriodStart).getTime()) / (1000 * 60 * 60 * 24)) % cycleSettings.avgCycleLength + 1
                        : '-'
                      }
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-white/50 text-xs">Twilight Garden</p>
                    <p className="text-white/30 text-[10px]">Your Health Companion</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default TodayReportModal;
